from .auth import router as auth
from .categories import router as categories
from .meanings import router as meanings
from .references import router as references
from .wordmeanings import router as wordmeanings
from .words import router as words
from .wordattachments import router as wordattachments
from .attachments import router as attachments
from .users import router as users
