from .attachments import router as attachments
from .auth import router as auth
from .categories import router as categories
from .meanings import router as meanings
from .references import router as references
from .users import router as users
from .wordattachments import router as wordattachments
from .wordmeanings import router as wordmeanings
from .words import router as words
from .wordcategory import router as wordcategory
