services:
  db:
    build:
      context: ./database
    restart: always
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <database>
      TZ: America/Sao_Paulo
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env.dev:/app/.env.dev
  proxy:
    build:
      context: ./
    image: waiwai-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites-available:/etc/nginx/sites-available
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/certs:/etc/certs
    networks:
      - api_proxy
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: on-failure
  api:
    image: waiwai-backend:latest
    restart: always
    networks:
      - api_proxy
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env.dev:/app/.env

networks:
  proxy:
    name: api_proxy
    external: true