services:
  db:
    build:
      context: ./database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <database>
      TZ: America/Sao_Paulo
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - ./database/postgresql.conf:/var/lib/postgresql/pgdata/postgresql.conf
  api:
    image: aejunior/waiwai-backend:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env.dev:/app/.env