# Use postgres/example user/password credentials

services:
  db:
    build:
      context: ./database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      TZ: America/Sao_Paulo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
