"""feat: usuarios com anexos

Revision ID: 2f7eaa9ffc0d
Revises: 83e7458f9606
Create Date: 2024-03-16 02:06:17.585774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7eaa9ffc0d'
down_revision: Union[str, None] = '83e7458f9606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###
