"""feat: tamanho de colunas em referências

Revision ID: 6d3db3012263
Revises: e799f5ce2314
Create Date: 2024-02-29 18:53:58.760171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3db3012263'
down_revision: Union[str, None] = 'e799f5ce2314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meanings', 'phonemic',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('meanings', 'comment',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meanings', 'comment',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('meanings', 'phonemic',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
