"""feat: campo de fonema em words

Revision ID: 83e7458f9606
Revises: fd66b6192836
Create Date: 2024-03-02 15:01:25.875801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e7458f9606'
down_revision: Union[str, None] = 'fd66b6192836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meanings', 'phonemic')
    op.add_column('words', sa.Column('phonemic', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'phonemic')
    op.add_column('meanings', sa.Column('phonemic', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
