"""fix: reference coluna opcional

Revision ID: af02759a9796
Revises: a92dcd43fdb7
Create Date: 2024-02-19 16:01:25.068420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af02759a9796'
down_revision: Union[str, None] = 'a92dcd43fdb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.drop_constraint('references_url_key', 'references', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('references_url_key', 'references', ['url'])
    op.alter_column('references', 'url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    # ### end Alembic commands ###
