"""feat: tipo de arquivo do anexo

Revision ID: b88c58faece2
Revises: 2f7eaa9ffc0d
Create Date: 2024-03-16 09:32:42.650236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88c58faece2'
down_revision: Union[str, None] = '2f7eaa9ffc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('content_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'content_type')
    # ### end Alembic commands ###
