"""feat: tamanho da coluna de referência

Revision ID: e799f5ce2314
Revises: af02759a9796
Create Date: 2024-02-29 09:56:02.560876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e799f5ce2314'
down_revision: Union[str, None] = 'af02759a9796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'reference',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=280),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'reference',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
