"""columns length updated

Revision ID: eaca3cd7ab60
Revises: 88cc2ed900c4
Create Date: 2024-05-09 13:46:16.395682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaca3cd7ab60'
down_revision: Union[str, None] = '88cc2ed900c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meanings', sa.Column('meaning_pt', sa.String(length=300), nullable=False))
    op.add_column('meanings', sa.Column('meaning_ww', sa.String(length=300), nullable=False))
    op.add_column('meanings', sa.Column('comment_pt', sa.String(length=800), nullable=True))
    op.add_column('meanings', sa.Column('comment_ww', sa.String(length=800), nullable=True))
    op.drop_column('meanings', 'chapter_id')
    op.drop_column('meanings', 'comment')
    op.drop_column('meanings', 'meaning')
    op.drop_column('meanings', 'entry_id')
    op.add_column('references', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('references', sa.Column('authors', sa.String(length=350), nullable=False))
    op.alter_column('references', 'reference',
               existing_type=sa.VARCHAR(length=280),
               type_=sa.String(length=350),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('references', 'reference',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=280),
               existing_nullable=False)
    op.drop_column('references', 'authors')
    op.drop_column('references', 'year')
    op.add_column('meanings', sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('meanings', sa.Column('meaning', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('meanings', sa.Column('comment', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('meanings', sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('meanings', 'comment_ww')
    op.drop_column('meanings', 'comment_pt')
    op.drop_column('meanings', 'meaning_ww')
    op.drop_column('meanings', 'meaning_pt')
    # ### end Alembic commands ###
