"""feat: campos na tabela de anexos

Revision ID: fb4331e72d63
Revises: b88c58faece2
Create Date: 2024-03-16 19:54:45.308334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4331e72d63'
down_revision: Union[str, None] = 'b88c58faece2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('attachments', sa.Column('filedir', sa.String(length=255), nullable=False))
    op.add_column('attachments', sa.Column('url', sa.String(length=255), nullable=False))
    op.drop_constraint('attachments_path_key', 'attachments', type_='unique')
    op.create_unique_constraint(None, 'attachments', ['url'])
    op.drop_column('attachments', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attachments', type_='unique')
    op.create_unique_constraint('attachments_path_key', 'attachments', ['path'])
    op.drop_column('attachments', 'url')
    op.drop_column('attachments', 'filedir')
    op.drop_column('attachments', 'filename')
    # ### end Alembic commands ###
